// Default app settings seeded for every company (additively synced on login).
export const setting_seed_data = {
  general: {
    chat: true,
    create_public_url_in_email: true,
    appearance: "Auto",
    default_mail: "Moon Mail Server",
  },

  modules: {
    invoice: true,
    proforma_invoice: true,
    estimate: true,
    delivery_challan: true,
    bill: true,
    credit_note: true,
    debit_note: true,
    expense: true,
    sales_receipt: true,
    packing_slip: true,
    time_log: true,
    purchase_order: true,
    project: true,
    team: true,
    payment_received: true,
    payment_made: true,
    integrations: true,
    banking: true,
    rewards: true,
    product: true,
    service: true,
    report: true,
    pos: false,
    my_documents: true,
  },

  currency_format: {
    currency: "$ USD",
    currency_symbol: true,
    currency_code: false,
    multi_currency_display: true,
    exchange_rates: true,
    decimal_places: 2,
    date_number_format: "English (United States)",
    language: "English",
    timezone: "(GMT-7:00) America/Los_Angeles",
  },

  printer: {
    print_mode: "Normal",
  },

  whatsApp: {
    enabled: true,
    send_via: "Moon Invoice",
  },

  notification: {
    timezone: "(GMT-7:00) America/Los_Angeles",
    notification_time: "07:00",
    recurring: {
      auto_send_invoice: true,
      daily: true,
      weekly: true,
      monthly: true,
    },
    payment_reminder: {
      auto_send_payment_receipt: true,
      default_for_new_customer: true,
      days_before_due_3: true,
      on_due_date: true,
      days_after_due_3: true,
      days_after_due_7: true,
    },
  },

  // ==================== INVOICE ====================
  invoice: {
    field_visibility: {
      due_date: true,
      shipping_address: true,
      internal_notes: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      po: true,
      po_date: true,
      recipient_name: true,
      shipping_cost_and_method: true,
      shipping_tax: true,
      salesperson: true,
      payment_methods: true,
      apply_discount_before_tax: true,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
      create_public_url_in_email: true,
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      quantity: "Show for Both",
      discount: true,
      mrp: true,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: true,
      description_in_suggestion_list: true,
      buy_price_in_suggestion_list: true,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      negative_value_format: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      custom_charges: false,
      inline_discount: true,
      show_line_total_with_tax: false,
    },
    print_email: {
      mark_as_sent_on_print: true,
      mark_as_sent_on_email_or_whatsApp: true,
      combine_pdf_in_email: true,
      number_of_copies_on_print: "Single Copy",
    },
    payment: {
      cash_received_denomination: false,
    },
  },

  // ==================== PROFORMA INVOICE ====================
  proforma_invoice: {
    field_visibility: {
      shipping_address: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      recipient_name: false,
      shipping_cost_and_method: true,
      shipping_tax: true,
      salesperson: false,
      apply_discount_before_tax: false,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      quantity: "Show for Both",
      discount: true,
      mrp: true,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: false,
      description_in_suggestion_list: false,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      custom_charges: false,
      inline_discount: true,
      show_line_total_with_tax: false,
    },
    print_email: {
      mark_as_sent_on_print: true,
      mark_as_sent_on_email_or_whatsApp: true,
      combine_pdf_in_email: true,
      number_of_copies_on_print: "Single Copy",
    },
  },

  // ==================== SALES RECEIPT ====================
  sales_receipt: {
    field_visibility: {
      shipping_address: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      recipient_name: false,
      shipping_cost_and_method: true,
      shipping_tax: true,
      salesperson: false,
      payment_type: true,
      apply_discount_before_tax: false,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      quantity: "Show for Both",
      discount: true,
      mrp: true,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: false,
      description_in_suggestion_list: false,
      buy_price_in_suggestion_list: true,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      negative_value_format: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      custom_charges: false,
      inline_discount: true,
      show_line_total_with_tax: false,
    },
    print_email: {
      combine_pdf_in_email: true,
      number_of_copies_on_print: "Single Copy",
    },
  },

  // ==================== ESTIMATE ====================
  estimate: {
    field_visibility: {
      shipping_address: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      recipient_name: false,
      shipping_cost_and_method: true,
      shipping_tax: true,
      salesperson: false,
      apply_discount_before_tax: false,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      quantity: "Show for Both",
      discount: true,
      mrp: true,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: false,
      description_in_suggestion_list: false,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      custom_charges: false,
      inline_discount: true,
      show_line_total_with_tax: false,
    },
    print_email: {
      mark_as_sent_on_print: true,
      mark_as_sent_on_email_or_whatsApp: true,
      combine_pdf_in_email: true,
      number_of_copies_on_print: "Single Copy",
    },
  },

  // ==================== DELIVERY CHALLAN ====================
  delivery_challan: {
    field_visibility: {
      shipping_address: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      recipient_name: false,
      salesperson: false,
      apply_discount_before_tax: false,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      discount: true,
      mrp: true,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: false,
      description_in_suggestion_list: false,
      buy_price_in_suggestion_list: true,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      negative_value_format: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      custom_charges: false,
      inline_discount: true,
      show_line_total_with_tax: false,
    },
    print_email: {
      combine_pdf_in_email: true,
      number_of_copies_on_print: "Single Copy",
    },
  },

  // ==================== PURCHASE ORDER ====================
  purchase_order: {
    field_visibility: {
      shipping_address: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      recipient_name: false,
      shipping_cost_and_method: true,
      apply_discount_before_tax: false,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
      track_purchase_orders_in_stock: false,
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      quantity: "Show for Both",
      discount: true,
      mrp: false,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: false,
      description_in_suggestion_list: false,
      sell_price_in_suggestion_list: true,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      negative_value_format: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      show_line_total_with_tax: false,
    },
    print_email: {
      mark_as_sent_on_print: true,
      mark_as_sent_on_email_or_whatsApp: true,
      combine_pdf_in_email: true,
      number_of_copies_on_print: "I will Choose ...",
    },
  },

  // ==================== BILL ====================
  bill: {
    field_visibility: {
      due_date: true,
      shipping_address: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      po: true,
      recipient_name: false,
      shipping_cost_and_method: true,
      apply_discount_before_tax: false,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      quantity: "Show for Both",
      discount: true,
      mrp: false,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: false,
      description_in_suggestion_list: false,
      sell_price_in_suggestion_list: true,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      negative_value_format: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      show_line_total_with_tax: false,
    },
    print_email: {
      mark_as_sent_on_print: true,
      mark_as_sent_on_email_or_whatsApp: true,
      combine_pdf_in_email: true,
      number_of_copies_on_print: "I will Choose ...",
    },
  },

  // ==================== CREDIT NOTE ====================
  credit_note: {
    field_visibility: {
      shipping_address: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      recipient_name: false,
      salesperson: false,
      apply_discount_before_tax: false,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      quantity: "Show for Both",
      discount: true,
      mrp: true,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: false,
      description_in_suggestion_list: false,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      negative_value_format: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      custom_charges: false,
      inline_discount: true,
      show_line_total_with_tax: false,
    },
    print_email: {
      combine_pdf_in_email: true,
      number_of_copies_on_print: "Single Copy",
    },
  },

  // ==================== DEBIT NOTE ====================
  debit_note: {
    field_visibility: {
      shipping_address: true,
      street1: true,
      street2: true,
      zip_code: true,
      city: true,
      state: true,
      country: true,
      sub_title: true,
      recipient_name: false,
      apply_discount_before_tax: false,
      terms_conditions: true,
      notes: true,
      attachment: true,
    },
    general: {
      line_option: "Both",
    },
    columns: {
      service_name: true,
      product_name: true,
      description: true,
      quantity: "Show for Both",
      discount: true,
      mrp: false,
      tax: true,
      line_description_full_width: true,
      stock_in_suggestion_list: false,
      description_in_suggestion_list: false,
      item_code_in_suggestion_list: true,
      auto_fit: true,
    },
    summary: {
      total_quantity: false,
      round_off: false,
      negative_value_format: false,
      subtotal_with_tax: "Default",
      contact_note_as_default_note: false,
      show_line_total_with_tax: false,
    },
    print_email: {
      combine_pdf_in_email: true,
      number_of_copies_on_print: "I will Choose ...",
    },
  },

  // ==================== EXPENSE ====================
  expense: {
    round_off: false,
    payment_type: true,
  },

  // ==================== PRODUCT ====================
  product: {
    field_visibility: {
      hsn: false,
      inventory: true,
      mrp: false,
    },
    general: {
      product_img_on_line_item: false,
      allow_zero_stock: true,
    },
    stock: {
      product_stock: true,
    },
  },

  // ==================== SERVICE ====================
  service: {
    sac: true,
  },

  // ==================== TIME LOG ====================
  time_log: {
    columns: {
      include_project_in_create_invoice: true,
      include_date_in_create_invoice: true,
      include_notes_in_create_invoice: true,
    },
    summary: {
      time_log_rounding: "0 mins",
    },
  },
};
